### LOGIN
PUT http://192.168.0.201/run HTTP/1.1
content-type: text/plain

LOGIN esplight

### STATS
GET http://192.168.0.201/stats HTTP/1.1


### BOOT
GET http://192.168.0.201/boot HTTP/1.1
### 
PUT http://192.168.0.201/boot HTTP/1.1
content-type: text/plain

< ./192.168.0.201/boot.txt


### ANIM01_L
GET http://192.168.0.201/scripts/anim01_l HTTP/1.1
###
PUT http://192.168.0.201/scripts/anim01_l HTTP/1.1
content-type: text/plain

< ./192.168.0.201/anim01_l.txt


### ANIM01_H
GET http://192.168.0.201/scripts/anim01_h HTTP/1.1
### 
PUT http://192.168.0.201/scripts/anim01_h HTTP/1.1
content-type: text/plain

< ./192.168.0.201/scripts/anim01_h.txt

### Tests
PUT http://192.168.0.201/run

TURN D3 1
###
GET http://192.168.0.201/run?file=anim01_h
###
PUT http://192.168.0.201/run

SEQ D5
SLIDE 100 20
SLIDE 100 200
REPEAT 2 -1
END
SEQ D6
SLIDE 100 20
SLIDE 100 200
REPEAT 2 -1
END
SEQ D7
SLIDE 100 20
SLIDE 100 200
REPEAT 2 -1
END
SEQ D8
SLIDE 100 20
SLIDE 100 200
REPEAT 2 -1
END
SEQ D9
SLIDE 100 20
SLIDE 100 200
REPEAT 2 -1
END

###
PUT http://192.168.0.201/run

SEQ D5
VALUE 128
END
SEQ D6
VALUE 128
END
SEQ D7
VALUE 128
END
SEQ D8
VALUE 128
END
SEQ D9
VALUE 128
END
###
PUT http://192.168.0.201/run

SEQ D5
VALUE 1023
END
###
PUT http://192.168.0.201/run

SEQ D5
VALUE 50
END
SEQ D6
VALUE 50
END
SEQ D7
VALUE 50
END
SEQ D8
VALUE 50
END
SEQ D9
VALUE 50
END
###
PUT http://192.168.0.201/run

SEQ D5
VALUE 1023
END
SEQ D6
VALUE 1023
END
SEQ D7
VALUE 1023
END
SEQ D8
VALUE 1023
END
SEQ D9
VALUE 1023
END
###