### LOGIN
PUT http://192.168.0.106/run HTTP/1.1
content-type: text/plain

LOGIN esplight

### STATS
GET http://192.168.0.106/stats HTTP/1.1


### BOOT
GET http://192.168.0.106/boot HTTP/1.1
### 
PUT http://192.168.0.106/boot HTTP/1.1
content-type: text/plain

NAME lights


### AP
PUT http://192.168.0.106/run HTTP/1.1

LOGIN esplight
WIFIAP 1

